all:
	@cd ./single_client; \
		make
	@cd ./single_process; \
		make
	@cd ./concurrent; \
		make

.PHONY:clean

clean:
	@cd ./single_client; \
		make clean
	@cd ./single_process; \
		make clean
	@cd ./concurrent; \
		make clean
